#pragma once

#include "core/frame_context.hpp"
#include "defines.hpp"
#include "math/math_types.hpp"
#include "memory/arena.hpp"
#include "resources/resource_types.hpp"
#include "utils/string.hpp"

struct Geometry_Render_Data
{
    mat4      model;
    Geometry *geometry;
};

struct UI_Render_Data
{
    struct ImDrawData *draw_list;
};

enum class Renderpass_Type : u8
{
    VIEWPORT,
    UI
};

// Renderer_Backend is the function pointer interface for renderer backends.
// Backends manage their own private state via internal state pointers.
struct Renderer_Backend
{
    u64 frame_number;

    // Lifecycle
    b8 (*initialize)(Arena                 *allocator,
                     struct Platform_State *platform,
                     String                 app_name);
    void (*shutdown)();
    void (*resized)(u16 width, u16 height);

    // Frame loop
    b8 (*begin_frame)(Frame_Context *frame_ctx, f32 delta_t);
    void (*update_global_viewport_state)(mat4 projection,
                                         mat4 view,
                                         vec3 view_position,
                                         vec4 ambient_colour,
                                         s32  mode);
    b8 (*end_frame)(Frame_Context *frame_ctx, f32 delta_t);

    b8 (*start_renderpass)(Frame_Context *frame_ctx, Renderpass_Type type);
    b8 (*finish_renderpass)(Frame_Context *frame_ctx, Renderpass_Type type);

    void (*draw_geometry)(Geometry_Render_Data data);
    void (*draw_ui)(UI_Render_Data data);

    // Resource management
    void (*create_texture)(const u8       *pixels,
                           struct Texture *texture,
                           b8              is_ui_texture);
    void (*destroy_texture)(struct Texture *texture);

    b8 (*create_material)(struct Material *material);
    void (*destroy_material)(struct Material *material);

    b8 (*create_geometry)(Geometry        *geometry,
                          u32              vertex_count,
                          const vertex_3d *vertices,
                          u32              index_count,
                          const u32       *indices);
    void (*destroy_geometry)(Geometry *geometry);

    // Viewport management
    void (*render_viewport)();
    void *(*get_rendered_viewport)();
    void (*resize_viewport)(u32 width, u32 height);
    void (*get_viewport_size)(u32 *width, u32 *height);
};

// Render packets may contain info needed to render a frame
// i.e. list of meshes, camera information etc.
struct Render_Context
{
    u32                   geometry_count;
    Geometry_Render_Data *geometries;
    UI_Render_Data        ui_data; // UI render data (generated by application,
                                   // rendered by backend)
};

enum class Renderer_Backend_Type
{
    VULKAN,
    OPENGL,
    DIRECTX
};
