#pragma once

#include "defines.hpp"
// This file contains declarations that are going to exposed to multiple
// subsystems Initially it contained the renderer backend defition too
#include "math/math_types.hpp"
#include "resources/resource_types.hpp"

// Nvidia graphics cards usually have a requirement that the global uniform
// objects have a size of 256 bytes, so we add some padding to respect that.
// Global_Uniform_Object gets uploaded once per frame

struct Geometry_Render_Data {
    mat4 model;
    Geometry* geometry;
};

struct UI_Render_Data {
    struct ImDrawData* draw_list;
};

enum class Renderpass_Type : u8 { VIEWPORT, UI };

// Renderer_backend is the interface of the renderer classes
struct Renderer_Backend {
    u64 frame_number;

    b8 (*initialize)(Renderer_Backend* backend, const char* app_name);
    void (*shutdown)(Renderer_Backend* backend);

    void (*resized)(Renderer_Backend* backend, u16 width, u16 height);

    b8 (*begin_frame)(Renderer_Backend* backend, f32 delta_t);
    void (*update_global_viewport_state)(mat4 projection,
        mat4 view,
        vec3 view_position,
        vec4 ambient_colour,
        s32 mode);
    b8 (*end_frame)(Renderer_Backend* backend, f32 delta_t);

    b8 (*start_renderpass)(Renderer_Backend* backend, Renderpass_Type type);
    b8 (*finish_renderpass)(Renderer_Backend* backend, Renderpass_Type type);

    void (*draw_geometry)(Geometry_Render_Data data);
    void (*draw_ui)(UI_Render_Data data);

    void (*create_texture)(const u8* pixels, struct Texture* texture);
    void (*destroy_texture)(struct Texture* texture);

    b8 (*create_material)(struct Material* material);
    void (*destroy_material)(struct Material* material);

    b8 (*create_geometry)(Geometry* geometry,
        u32 vertex_count,
        const vertex_3d* vertices,
        u32 index_count,
        const u32* indices);
    void (*destroy_geometry)(Geometry* geometry);
};

// Render packets may contain info needed to render a frame
// i.e. list of meshes, camera information etc.
struct Render_Packet {
    f32 delta_time;

    u32 geometry_count;
    Geometry_Render_Data* geometries;

    // UI render data (generated by application, rendered by backend)
    UI_Render_Data ui_data;
};

enum class Renderer_Backend_Type { VULKAN, OPENGL, DIRECTX };
